Add user unit test
chingu-voyage3/bears-21 pull request #95
Opened 2018-02-10 23:49 UTC by nikrb

added user unit tests, front and back

2018-02-11 01:35 UTC, nikrb commented
looks like redux search actions were moved to Search directory but left in actions in Redux directory ... so I've removed the duplicates in the Redux directory.

2018-02-11 11:01 UTC, Mortuie requested changes

2018-02-11 11:01 UTC, Mortuie commented on frontend/src/Redux/reducers.js
> +  user: userReducer,
Do we need this inconsistency? can't we just have `userReducer` or `user` to follow the suit of the others?

2018-02-14 20:43 UTC, Mortuie approved these changes

2018-02-14 21:02 UTC, merged